// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmKZJevPNYH-sP93_v9HGdEhOvkII-n4',
    appId: '1:806227566965:web:a4f31592fd041dee44f33c',
    messagingSenderId: '806227566965',
    projectId: 'accessx-afc83',
    authDomain: 'accessx-afc83.firebaseapp.com',
    databaseURL: 'https://accessx-afc83-default-rtdb.firebaseio.com',
    storageBucket: 'accessx-afc83.firebasestorage.app',
    measurementId: 'G-Y46P3F68WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpt6tyDLWUuqrRSI_dCnJD1zQOz_SjE8',
    appId: '1:806227566965:android:a3b47834ba7cbef844f33c',
    messagingSenderId: '806227566965',
    projectId: 'accessx-afc83',
    databaseURL: 'https://accessx-afc83-default-rtdb.firebaseio.com',
    storageBucket: 'accessx-afc83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsrzshSqIjY1vpAOObooIPEIosQm5--c',
    appId: '1:806227566965:ios:4830e83768a8e48d44f33c',
    messagingSenderId: '806227566965',
    projectId: 'accessx-afc83',
    databaseURL: 'https://accessx-afc83-default-rtdb.firebaseio.com',
    storageBucket: 'accessx-afc83.firebasestorage.app',
    iosBundleId: 'com.norah.mobileproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsrzshSqIjY1vpAOObooIPEIosQm5--c',
    appId: '1:806227566965:ios:3d82bdb95cc9ba9344f33c',
    messagingSenderId: '806227566965',
    projectId: 'accessx-afc83',
    databaseURL: 'https://accessx-afc83-default-rtdb.firebaseio.com',
    storageBucket: 'accessx-afc83.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmmKZJevPNYH-sP93_v9HGdEhOvkII-n4',
    appId: '1:806227566965:web:9a37c4a572b2c41a44f33c',
    messagingSenderId: '806227566965',
    projectId: 'accessx-afc83',
    authDomain: 'accessx-afc83.firebaseapp.com',
    databaseURL: 'https://accessx-afc83-default-rtdb.firebaseio.com',
    storageBucket: 'accessx-afc83.firebasestorage.app',
    measurementId: 'G-QEQ2P9T9JZ',
  );
}
